[tool.poetry]
name = "boligascraper"
version = "0.1.0"
description = ""
authors = ["Henrik Christoffersen"]

packages = [
    { include = "scraper", from = "src" },
    { include = "helper", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7.1"
MechanicalSoup = "^1.0.0"
pandas = "^1.2.2"
geopy = "^2.1.0"
XlsxWriter = "^1.3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
