[tool.poetry]
name = "boliga-scraper"
version = "0.1.0"
description = ""
authors = ["Henrik Christoffersen"]

packages = [
    { include = "scraper", from = "src" },
    { include = "reporting", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7.1"
MechanicalSoup = "^1.0.0"
pandas = "^1.2.2"
geopy = "^1.2"
pretty-html-table = "^0.9.dev0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
